# Generated by Django 3.2.9 on 2021-11-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.TimeField()),
                ('leave_time', models.TimeField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=200)),
                ('current_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_police', to='manager.mission')),
                ('missions', models.ManyToManyField(related_name='all_police', through='manager.MissionPolice', to='manager.Mission')),
            ],
        ),
        migrations.AddField(
            model_name='missionpolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.police'),
        ),
    ]
