# Generated by Django 3.2.9 on 2021-11-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20211113_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionpolice',
            name='leave_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='current_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_police', to='manager.mission'),
        ),
        migrations.AlterField(
            model_name='police',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
