# Generated by Django 3.2.9 on 2021-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20211113_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='missionpolice',
            name='join_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='missionpolice',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
