# Generated by Django 3.2.9 on 2021-11-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20211116_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=200, null=True),
        ),
    ]
